name: Sync Fork All

on:
  workflow_dispatch: # on button click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: borisko123/manageiq
          path: local_manageiq
      - name: clone manageiq  
        run: |
          pwd
          ls -al
          cd local_manageiq
          date > generated.txt
          ls -al
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
        env:
          REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
       
