name: Sync Fork All

on:
  workflow_dispatch: # on button click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: borisko123/manageiq
          path: local_manageiq
          token: ${{secrets.PAT_FOR_PUSH}} 
      - name: clone manageiq  
        run: |
          echo "start clone manageiq and push"
          git remote -v
          pwd
          ls -al
          cd local_manageiq
          date > generated.txt
          ls -al
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push https://$USERNAME:REPO_KEY@github.com/borisko123/manageiq.git master
        env:
          REPO_KEY: ${{secrets.PAT_FOR_PUSH}}
          USERNAME: bk-git-actions
       
