name: Sync Fork All

on:
  workflow_dispatch: # on button click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: borisko123/manageiq
          path: local-manageiq
      - run: |
          pwd
          ls -al
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git log
          ls -al
